services:

  mysql:
    image: mysql:9.5.0
    container_name: contele-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - main:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
    profiles: ["dev"]
    ports:
    - ${MYSQL_PORT}:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - private

  control-posts:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: control-posts
    volumes:
      - control-posts-node-modules:/app/node_modules
      - ./:/app
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WRITER_MYSQL_HOST: mysql
      WRITER_MYSQL_PASS: ${WRITER_MYSQL_PASS}
      WRITER_MYSQL_PORT: ${WRITER_MYSQL_PORT}
      WRITER_MYSQL_USER: ${WRITER_MYSQL_USER}
      WRITER_MYSQL_DATABASE: ${WRITER_MYSQL_DATABASE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      LOG_DIR: ${LOG_DIR}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - 8081:8081
      - 9229:9229
    networks:
      - public
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  control-posts-node-modules:
  main:
      