version: '3.5'

services:

  mysql:
    image: mysql:latest
    container_name: contele-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - main:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - ${MYSQL_PORT}:3305
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 5

  control-posts:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: control-posts
    working_dir: /control-posts
    volumes:
      - control-posts-node-modules:/control-posts/node_modules
      - ./:/control-posts
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WRITER_MYSQL_HOST: ${MYSQL_HOST}
      WRITER_MYSQL_PASS: ${MYSQL_PASSWORD}
      WRITER_MYSQL_PORT: ${DB_PORT}
      WRITER_MYSQL_USER: ${MYSQL_USER}
      WRITER_MYSQL_DATABASE: ${MYSQL_DATABASE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    links:
      - mysql:mysql
    ports:
      - 8081:8081
      - 9229:9229

volumes:
  control-posts-node-modules:
  main:
      